# Generated by Django 4.2.2 on 2023-06-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformasiKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('jabatan', models.CharField(max_length=50)),
                ('status_sertifikasi', models.CharField(max_length=50)),
                ('status_kuasa_hukum', models.CharField(max_length=50)),
                ('izin_berlaku_attorney', models.DateField()),
                ('izin_berlaku_konsultan', models.DateField()),
            ],
        ),
    ]
