# Generated by Django 4.2.2 on 2023-06-16 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='informasi_karyawan',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dashboard.informasikaryawan'),
            preserve_default=False,
        ),
    ]
