# Generated by Django 4.2.2 on 2023-06-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_notifications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informasikaryawan',
            name='izin_berlaku_attorney',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='informasikaryawan',
            name='izin_berlaku_konsultan',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
