# Generated by Django 4.2.2 on 2023-06-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_informasikaryawan_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifikasiAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesan', models.TextField()),
                ('informasi_karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.informasikaryawan')),
            ],
        ),
    ]
