# Generated by Django 4.2.2 on 2023-06-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_notifikasiadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotifikasiAdmin',
            new_name='AdminNotifications',
        ),
    ]
