# Generated by Django 4.2.2 on 2023-06-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_adminnotifications_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informasikaryawan',
            name='jabatan',
            field=models.CharField(choices=[('Partner', 'Partner'), ('Senior Manager', 'Senior Manager'), ('Manager', 'Manager'), ('Assistant Manager', 'Assistant Manager'), ('Senior Specialist', 'Senior Specialist'), ('Specialist', 'Specialist'), ('Admin', 'Admin')], max_length=50),
        ),
        migrations.AlterField(
            model_name='informasikaryawan',
            name='status_kuasa_hukum',
            field=models.CharField(choices=[('Ya', 'Ya'), ('Bukan Kuasa Hukum', 'Bukan Kuasa Hukum')], max_length=50),
        ),
        migrations.AlterField(
            model_name='informasikaryawan',
            name='status_sertifikasi',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('Bukan Konsultan Pajak', 'Bukan Konsultan Pajak')], max_length=50),
        ),
    ]
