# Generated by Django 4.2.2 on 2023-06-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_notifications_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('Karyawan Baru', 'Karyawan Baru'), ('Karyawan Keluar', 'Karyawan Keluar'), ('Jabatan', 'Jabatan'), ('Status dan Izin', 'Status dan Izin'), ('Projek', 'Projek')], max_length=50),
        ),
    ]
