# Generated by Django 4.2.2 on 2023-06-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_notifications_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informasikaryawan',
            name='status_kuasa_hukum',
            field=models.CharField(choices=[('Ya', 'Ya'), ('Bukan Kuasa Hukum', 'Bukan Kuasa Hukum')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='informasikaryawan',
            name='status_sertifikasi',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('Bukan Konsultan Pajak', 'Bukan Konsultan Pajak')], max_length=50, null=True),
        ),
    ]
