# Generated by Django 4.2.2 on 2023-06-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_notifications_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('Karyawan Baru', 'Karyawan Baru'), ('Karyawan Keluar', 'Karyawan Keluar'), ('Jabatan', 'Jabatan'), ('Informasi Personal', 'Informasi Personal'), ('Projek', 'Projek')], max_length=50),
        ),
    ]
