# Generated by Django 4.2.2 on 2023-06-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_notifications_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informasikaryawan',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Need Revision', 'Need Revision'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
