# Generated by Django 4.2.2 on 2023-06-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_informasikaryawan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='informasikaryawan',
            name='pesan',
            field=models.TextField(default=None),
        ),
    ]
