# Generated by Django 4.2.2 on 2023-06-28 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_informasikaryawan_pesan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informasikaryawan',
            name='pesan',
        ),
    ]
