# Generated by Django 4.2.2 on 2023-06-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_informasikaryawan_pesan'),
    ]

    operations = [
        migrations.AddField(
            model_name='informasikaryawan',
            name='pesan',
            field=models.TextField(default=None),
        ),
    ]
