# Generated by Django 4.2.2 on 2023-06-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_informasikaryawan_pesan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informasikaryawan',
            name='pesan',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
