# Generated by Django 4.2.2 on 2023-06-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150)),
                ('nama', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('role', models.CharField(max_length=50, verbose_name=[('Super Admin', 'Super Admin'), ('Senior Manager', 'Senior Manager'), ('Manager', 'Manager'), ('Assistant Manager', 'Assistant Manager'), ('Professional', 'Professional')])),
                ('jabatan', models.CharField(max_length=150)),
                ('pendidikan_terakhir', models.CharField(max_length=50, verbose_name=[('Sekolah Dasar', 'Sd'), ('Sekolah Menengah Pertama', 'Smp'), ('Sekolah Menengah Atas', 'Sma'), ('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')])),
                ('status_sertifikasi', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('Tidak Ada', 'Bukan Konsultan Pajak')], max_length=50)),
                ('status_kuasa_hukum', models.CharField(choices=[('Ya', 'Kuasa Hukum'), ('Tidak', 'Bukan Kuasa Hukum')], max_length=51)),
                ('izin_berlaku', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
