# Generated by Django 4.2.2 on 2023-06-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_is_staff_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='izin_berlaku',
            field=models.DateField(default=None),
        ),
    ]
