# Generated by Django 4.2.2 on 2023-06-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pendidikan_terakhir',
            field=models.CharField(choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA'), ('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Senior Manager', 'Senior Manager'), ('Assistant Manager', 'Assistant Manager'), ('Manager', 'Manager'), ('Professional', 'Professional')], max_length=50),
        ),
    ]
